version: "3"
services:
  nginx:
    build: nginx/.
    ports:
      - 80:80
    links:
      - node1
      - node2
  node1:
    image: moonchild/nodejsapp:v1.0.0
    container_name: my-node1
    links:
      - redis
    ports:
      - "9090"
  node2:
    image: moonchild/nodejsapp:v1.0.0
    container_name: my-node2
    links:
      - redis
    ports:
      - "9090"
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis-server
